openapi: 3.0.0
info:
  title: TN Data Workload API 
  description: |-
    This API enables the management of data processing workloads within a data platform. It provides endpoints for creating, updating, deleting, and retrieving workflows, as well as monitoring their status and performance.
    
    Some useful links:
    - [API Repository](https://github.com/bastoska/plataforma-dados-api)
  version: 1.0.0
servers:
  - url: https://bastoska.github.io/plataforma-dados-api/
    description: Development server
tags:
  - name: workloads
    description: Everything about your Workloads
  - name: tag_example
    description: tag_example description
paths:
  /workloads:
    get:
      tags:
        - workloads
      summary: Summary of the GET endpoint
      description: Description of what this endpoint does
      parameters:
        - name: param1
          in: query
          description: Description of param1
          required: true
          schema:
            type: string
            example: example1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  key1:
                    type: string
                    example: value1
                  key2:
                    type: integer
                    example: 123
        '400':
          description: Bad request
    post:
      tags:
        - workloads
      summary: Summary of the POST endpoint
      description: Description of what this endpoint does
      requestBody:
        description: Description of the request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                param1:
                  type: string
                  example: value1
                param2:
                  type: integer
                  example: 123
      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 123
        '400':
          description: Bad request
  /endpoint2:
    post:
      tags:
        - tag_example
      summary: Summary of the POST endpoint
      description: Description of what this endpoint does
      requestBody:
        description: Description of the request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                param1:
                  type: string
                  example: value1
                param2:
                  type: integer
                  example: 123
      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 123
        '400':
          description: Bad request
  /endpoint3/{id}:
    put:
      tags:
        - tag_example
      summary: Summary of the PUT endpoint
      description: Description of what this endpoint does
      parameters:
        - name: id
          in: path
          description: ID of the resource to update
          required: true
          schema:
            type: string
            example: 123
      requestBody:
        description: Description of the request body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                param1:
                  type: string
                  example: value1
                param2:
                  type: integer
                  example: 123
      responses:
        '200':
          description: Resource updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  key1:
                    type: string
                    example: value1
                  key2:
                    type: integer
                    example: 123
        '404':
          description: Resource not found
components:
  schemas:
    ExampleSchema:
      type: object
      properties:
        field1:
          type: integer
          format: int64
          example: 10
        field2:
          type: integer
          format: int64
          example: 198772
        field3:
          type: integer
          format: int32
          example: 7
        field4:
          type: string
          format: date-time
        field5:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        field6:
          type: boolean
      xml:
        name: order
